import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {
          `
          .home-title{
            color : red
          }
          h3{
            font-size : 28px
          }
          `
        }
      </style>
      <Head>
        <title>Hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className="text-4xl font-bold pt-8 home-title">
         Hunting coder
        </h1>

        <p className="text-2xl font-bold py-8">
        A blog for coders by a coder
        </p>
        <div>
          <h3>Learning next js in 2022</h3>
          <p>Js is the language of web ui, learn it better!</p>
        </div>
        <div>
          <h3>Learning next js in 2022</h3>
          <p>Js is the language of web ui, learn it better!</p>
        </div>
        <div>
          <h3>Learning next js in 2022</h3>
          <p>Js is the language of web ui, learn it better!</p>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
