import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainNav}>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Blog</li>
          <li>Content</li>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1>
         Hunting coder
        </h1>

        <p className={styles.description}>
        A blog for coders by a coder
        </p>
        <div>
          <h3>Learning next js in 2022</h3>
          <p>Js is the language of web ui, learn it better!</p>
        </div>
        <div>
          <h3>Learning next js in 2022</h3>
          <p>Js is the language of web ui, learn it better!</p>
        </div>
        <div>
          <h3>Learning next js in 2022</h3>
          <p>Js is the language of web ui, learn it better!</p>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
